# Generated by Django 6.0.1 on 2026-03-06 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anualIncome', models.IntegerField(blank=True, null=True)),
                ('marrage', models.CharField(blank=True, max_length=10, null=True)),
                ('children', models.IntegerField(blank=True, null=True)),
                ('education', models.CharField(blank=True, max_length=10, null=True)),
                ('occupation', models.CharField(blank=True, max_length=10, null=True)),
                ('otherpolicy', models.CharField(blank=True, max_length=10, null=True)),
                ('changePolicy', models.CharField(blank=True, max_length=10, null=True)),
                ('clientRating', models.IntegerField(blank=True, null=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clients_as_agent', to='adminapp.users')),
                ('campain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.campain')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_profiles', to='adminapp.users')),
            ],
        ),
    ]
