# Generated by Django 6.0.1 on 2026-03-07 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agentapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='policynumber',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
