# Generated by Django 6.0.1 on 2026-03-10 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='aadhar',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
